# Generated by promptly's release workflow; see scripts/release.js.
class Promptly < Formula
  desc "Procedural generative art for your zsh prompt"
  homepage "https://github.com/yungibly/promptly"
  version "0.7.0"

  on_macos do
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/yungibly/promptly/releases/download/v0.7.0/promptly-0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "1eabb7ccc914b0adbcff7820ea502fb3331dab91bde18a2f0587027d257266fe"
    end
    on_intel do
      url "https://github.com/yungibly/promptly/releases/download/v0.7.0/promptly-0.7.0-x86_64-apple-darwin.tar.gz"
      sha256 "3a1cb9775b0f24a39e066ffbe886f5c7c8053e98ebee0029468cf8ece498876e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yungibly/promptly/releases/download/v0.7.0/promptly-0.7.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9b7f38a81208ed6606a1db18eb1a09b7bcef5f9681e4d5ff6e00ecd118b97218"
    end
    on_intel do
      url "https://github.com/yungibly/promptly/releases/download/v0.7.0/promptly-0.7.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a1b9423341a0d1a1811c9bc474dbbefb9c15639731a9a4883a38d8f9a02c8abf"
    end
  end

  uses_from_macos "zsh"

  def install
    bin.install "promptly"
    doc.install "README.md", "bun-LICENSE.md", "THIRD_PARTY.md"
  end

  test do
    assert_equal "promptly #{version}", shell_output("#{bin}/promptly --version").strip
    # Keep this test portable to Homebrew environments without a UTF-8 locale.
    source = shell_output("#{bin}/promptly --seed homebrew --engine prompt --label brew --glyphs ascii")
    assert_match "# Promptly", source
    (testpath/"prompt.zsh").write(source)
    system "zsh", "-fn", testpath/"prompt.zsh"
    output = shell_output("zsh -f -c 'COLUMNS=80; source ./prompt.zsh; print -rP -- \"$PROMPT\"; promptly_off'")
    assert_match "brew", output
  end
end
