# Generated by promptly's release workflow; see scripts/release.js.
class Promptly < Formula
  desc "Procedural generative art for your zsh prompt"
  homepage "https://github.com/yungibly/promptly"
  version "0.5.1"

  on_macos do
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/yungibly/promptly/releases/download/v0.5.1/promptly-0.5.1-aarch64-apple-darwin.tar.gz"
      sha256 "cd867ff9433454d9b9aa240760be62fb7237e7db42c046219b3ce5df3c68e773"
    end
    on_intel do
      url "https://github.com/yungibly/promptly/releases/download/v0.5.1/promptly-0.5.1-x86_64-apple-darwin.tar.gz"
      sha256 "f2d83db49e22d5b5acb698440bd4523a0901bb586d8194511ad476c966369aab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yungibly/promptly/releases/download/v0.5.1/promptly-0.5.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "578c3ddf31d8706cb1c728e5d8010267d86ae9ef1a0f11bd3ced5768c4541c0b"
    end
    on_intel do
      url "https://github.com/yungibly/promptly/releases/download/v0.5.1/promptly-0.5.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b26327de936230e9f7242ddedd71dc4ca8fc6143465826c54b4cbf5bf6c82da0"
    end
  end

  uses_from_macos "zsh"

  def install
    bin.install "promptly"
    doc.install "README.md", "bun-LICENSE.md", "THIRD_PARTY.md"
  end

  test do
    assert_equal "promptly #{version}", shell_output("#{bin}/promptly --version").strip
    # Keep this test portable to Homebrew environments without a UTF-8 locale.
    source = shell_output("#{bin}/promptly --seed homebrew --engine prompt --label brew --glyphs ascii")
    assert_match "# Promptly", source
    (testpath/"prompt.zsh").write(source)
    system "zsh", "-fn", testpath/"prompt.zsh"
    output = shell_output("zsh -f -c 'COLUMNS=80; source ./prompt.zsh; print -rP -- \"$PROMPT\"; promptly_off'")
    assert_match "brew", output
  end
end
