# Generated by promptly's release workflow; see scripts/release.js.
class Promptly < Formula
  desc "Procedural generative art for your zsh prompt"
  homepage "https://github.com/yungibly/promptly"
  version "0.6.0"

  on_macos do
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/yungibly/promptly/releases/download/v0.6.0/promptly-0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "71f18b37f16d88d56939d87ff6d1adea285ad52df05ab9e046893dca1bf87e2b"
    end
    on_intel do
      url "https://github.com/yungibly/promptly/releases/download/v0.6.0/promptly-0.6.0-x86_64-apple-darwin.tar.gz"
      sha256 "6c6d956a9fffd1902c9b186ab9240509413d5ccb3b0664f043a37fc246a9f314"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yungibly/promptly/releases/download/v0.6.0/promptly-0.6.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1bfa5a6714532626e582a26582cbfeedfb22b30c5e09547e5a5b02234ad3a7b5"
    end
    on_intel do
      url "https://github.com/yungibly/promptly/releases/download/v0.6.0/promptly-0.6.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "542d2ff43e06530d321985d0fcf79fd4e465d61d601c4aa36028aa441fe08034"
    end
  end

  uses_from_macos "zsh"

  def install
    bin.install "promptly"
    doc.install "README.md", "bun-LICENSE.md", "THIRD_PARTY.md"
  end

  test do
    assert_equal "promptly #{version}", shell_output("#{bin}/promptly --version").strip
    # Keep this test portable to Homebrew environments without a UTF-8 locale.
    source = shell_output("#{bin}/promptly --seed homebrew --engine prompt --label brew --glyphs ascii")
    assert_match "# Promptly", source
    (testpath/"prompt.zsh").write(source)
    system "zsh", "-fn", testpath/"prompt.zsh"
    output = shell_output("zsh -f -c 'COLUMNS=80; source ./prompt.zsh; print -rP -- \"$PROMPT\"; promptly_off'")
    assert_match "brew", output
  end
end
